[package]
name = "thumbnailer"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.31", features = ["derive"] }
image = { version = "0.25.5" }
thumbnailify = { path = "../thumbnailify" }
