name: Rust

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - .gitignore
      - "*.md"
      - ".github/screenshots/**"
  push:
    paths-ignore:
      - .gitignore
      - "*.md"
      - ".github/screenshots/**"
    
env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-24.04
          - ubuntu-24.04-arm

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
        
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: 1.85
      
      - name: Install Deps
        run: sudo apt-get update && sudo apt-get install -y libdav1d-dev

      - name: Build
        run: cargo build
      
      - name: Run tests
        run: cargo test --verbose

  build-static:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-24.04
            target: x86_64-unknown-linux-musl
          - os: ubuntu-24.04-arm
            target: aarch64-unknown-linux-musl

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
        
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: 1.85
          target: ${{ matrix.target }}

      - name: Build
        run: cargo build --target ${{ matrix.target }}
      
      - name: Run tests
        run: cargo test --verbose